/*
 * update.h
 *
 *  Created on: 13. 2. 2017
 *      Author: ondra
 */

#pragma once

#include "json.h"

namespace couchit {

///Contains result of external update procesude
class UpdateResult {
public:
	UpdateResult();
	///Construct the object from the response
	UpdateResult(const Value &result, const String &contentType, const String &rev);
	///Retrieves content as binary string
	/**
	 * @return Function receives response as binary string - this function
	 * works only if the response is not json. To determine, whether response
	 * is json use function isJSON()
	 */
	BinaryView getContent() const;

	///Retrieves content as json
	/**
	 * @return Function receives response as JSON - this function
	 * works only if the response is JSON. To determine, whether response
	 * is json use function isJSON()
	 */
	Value getJSONContent() const;
	///Retrieves content type of the response
	/**
	 * @return Content type of response. In case the result is JSON, function returns "application/json".
	 */
	String getContentType() const;
	///Retrieves revision of update
	/**
	 * @return new revision ID of the document
	 */
	String getRev() const;
	///Determines whether response is JSON
	/**
	 * @retval false response is not JSON. The function getContent() returns binary response
	 * @retval true response is JSON.
	 */
	bool isJSON();
protected:
	Value result;
	String contentType;
	String rev;

};


///Declaration of external update procedure
class UpdateProc{
public:

	///Declares procedure by specifiing the path to the procedure
	UpdateProc(const String path);
	///Executes external update
	/**
	 * @param db specified database instance on which the external procedure will be executed
	 * @param docId specifies document-id on which the update will be executed. Document don't need to exist.
	 * @param arguments an arguments passed to the update function.
	 * @return result generated by update procedure. The procedure can return either JSON or binary
	 *  response. The class UpdateResult can handle both types of result
	 */
	UpdateResult operator()(CouchDB &db, StrViewA docId, Value arguments = json::undefined);

protected:
	String path;

};


}





